### ISSUE TITLE
[Bug]: Turin GTT realtime data not applied as ref. by stop_sequence

### ISSUE THREAD

**Issue by vingerha** [vingerha/gtfs2#119]
### Own Analysis

- [X] I cannot find my issue in the documentation

### A clear and concise description of what the bug is.

```shell
GTFS rt from GTT does not supply their data with stop_id but with stop_sequence
Example;

[
    {
        "id": "26232766U",
        "trip_update": {
            "trip": {
                "trip_id": "26232766U",
                "start_time": "07:38:00",
                "start_date": "20241231",
                "route_id": "",
                "direction_id": "0"
            },
            "stop_time_update": [
                {
                    "stop_sequence": 3,
                    "stop_id": "",
                    "arrival": {
                        "delay": 0,
                        "time": 0
                    },
                    "departure": {
                        "delay": 0,
                        "time": 1735627147
                    }
```

### Provide details on the data source(s)

```shell
http://percorsieorari.gtt.to.it/das_gtfsrt/alerts.aspx
```

### Info on your installed version

last dev

**Comment by vingerha** [comment]
@mrloddo Can you please verify with https://github.com/vingerha/gtfs2/releases/tag/0.5.4

**Comment by mrloddo** [comment]
I installed again the 0.5.4 but im confused about what I have to
check.



Marco


-----Original message-----
From: Arjan ***@***.***
Date: Tue, 31 Dec 2024 16:55:06 +0100
To: vingerha/gtfs2 ***@***.***
Subject: Re: [vingerha/gtfs2] [Bug]: Turin GTT realtime data not
applied asref. by stop_sequence (Issue #119)

> @mrloddo Can you please verify with
https://github.com/vingerha/gtfs2/releases/tag/0.5.4

**Comment by vingerha** [comment]
The new version will show realtime departures for your stop....assuming you got the RT link setup.
With me it works but prefer a confirmation of the actual user :)

![image](https://github.com/user-attachments/assets/bd79abfc-167d-4a8d-ae7c-b49c54a1c320)

**Comment by vingerha** [comment]
And I made a mistake.... 0.5.5dev4...apologies 
https://github.com/vingerha/gtfs2/releases/tag/0.5.5dev4

**Comment by mrloddo** [comment]
Uhm, I installed the 0.5.5dev4 and I set the gtfs in this way:
![image](https://github.com/user-attachments/assets/205305e5-4665-4ecd-bdfd-569bbfeb98cb)
![image](https://github.com/user-attachments/assets/0ca002c1-03ec-4cb5-915b-ed2d3558204f)

I don't see any realtime info in any departures lines
![image](https://github.com/user-attachments/assets/ec59698a-b8fe-4794-93eb-694ba56c9c12)

**Comment by vingerha** [comment]
Depending on the provider it comes and goes, I cannot check this all day long as you understand...just shown you my result above so .... do check more often.
Here in the south of France one just has to hope that:
- the provider offers the data
- the data is not old
- the link has not changed
- the site is working
- etc.

**Comment by vingerha** [comment]
And it updates too with me
![image](https://github.com/user-attachments/assets/81288462-2a4c-4042-8aa7-1fa6f0547751)

This is my sensor content
```
gtfs_updated_at: "2024-12-31T18:14:18.623053+00:00"
device_tracker_id: zone.turinrivodora
offset: 0
next_departures_lines:
  - departure: "19:16"
    departure_datetime: "2024-12-31T18:16:47+00:00"
    departure_realtime: "19:17"
    departure_realtime_datetime: "2024-12-31T18:17:12+00:00"
    delay_realtime_derived: "0:00:25"
    delay_realtime: "-"
    date: "2024-12-31"
    stop_name: Fermata 2519 - RIVODORA
    route: "8"
    route_long: via Mezzaluna (San Mauro) - corso Bolzano
    headsign: PORTA SUSA, CORSO BOLZANO
    trip_id: 26237094U
    direction_id: 1
    icon: mdi:bus
  - departure: "19:26"
    departure_datetime: "2024-12-31T18:26:11+00:00"
    departure_realtime: "-"
    departure_realtime_datetime: "-"
    delay_realtime_derived: "-"
    delay_realtime: "-"
    date: "2024-12-31"
    stop_name: Fermata 2519 - RIVODORA
    route: "3107"
    route_long: Torino - Settimo - Gassino - Chivasso - Piova' Massaia
    headsign: FIOCHETTO
    trip_id: 1877263E
    direction_id: 1
    icon: mdi:bus
  - departure: "19:32"
    departure_datetime: "2024-12-31T18:32:47+00:00"
    departure_realtime: "-"
    departure_realtime_datetime: "-"
    delay_realtime_derived: "-"
    delay_realtime: "-"
    date: "2024-12-31"
    stop_name: Fermata 2519 - RIVODORA
    route: "8"
    route_long: via Mezzaluna (San Mauro) - corso Bolzano
    headsign: PORTA SUSA, CORSO BOLZANO
    trip_id: 26237118U
    direction_id: 1
    icon: mdi:bus
  - departure: "19:34"
    departure_datetime: "2024-12-31T18:34:47+00:00"
    departure_realtime: "-"
    departure_realtime_datetime: "-"
    delay_realtime_derived: "-"
    delay_realtime: "-"
    date: "2024-12-31"
    stop_name: Fermata 2519 - RIVODORA
    route: "61"
    route_long: via Mezzaluna (San Mauro) - corso Vittorio Emanuele II
    headsign: PORTA NUOVA, C. VITTORIO EMANUELE II
    trip_id: 26235248U
    direction_id: 1
    icon: mdi:bus
latitude: 45.1127
longitude: 7.779
friendly_name: 1675_local_stop_zone.turinrivodora
```
