### ISSUE TITLE
[FEATURE]: Add source for Bilbao

### ISSUE THREAD

**Issue by davidclaeysquinones** [vingerha/gtfs2#87]
The city of Bilbao provides sources for it's public bus service at [this](https://www.euskadi.eus/gtfs-informacion-autobuses-bilbobus/web01-a2gizar/es/) site. Can it be used out of the box ?

Edit:
There are even more sources available :

[Bilbobus (euskadi.eus)](https://www.euskadi.eus/gtfs-informacion-autobuses-bilbobus/web01-a2gizar/es/)
[Bilbobus (data.ctb.eus)](https://data.ctb.eus/dataset/horario-lineas-bilbobus)
[Metro Bilbao](https://www.euskadi.eus/gtfs-informacion-autobuses-bilbobus/web01-a2gizar/es/)
[Renfe Cercanias](https://data.ctb.eus/dataset/horarios-renfe-cercanias/resource/e364957e-26a0-42c2-b0a8-2102953b31fc)
[Bus Bilbao-Vitoria](https://data.ctb.eus/dataset/horarios-la-union-bilbao-vitoria-por-autopista)

This isn't even the complete list ([complete list](https://data.ctb.eus/dataset?res_format=GTFS))

**Comment by vingerha** [comment]
You can always try else look at gtfs.pro

**Comment by FabienD74** [comment]
Hi davidclaeysquinones

Everything worked ? 
Let us now wich gtfs ( url link to zip ) , ....

Thx
Fabien

**Comment by davidclaeysquinones** [comment]
I tried gtfs.pro and it works fine :)
I just wish I was able to filter bus stops.
<img width="388" alt="image" src="https://github.com/vingerha/gtfs2/assets/15612887/3f079441-3f94-40ac-bab5-00822a94a97e">
Now I'm seeing multiple bus stops that are near my house, but actually I only want Lehendakari Aguirre 135.

```
 - type: custom:auto-entities
    filter:
      include:
        - name: '*local_stop_zone.sarriko*'
      exclude:
        - state: unavailable
        - attributes:
            stop_name: '! LEHENDAKARI AGUIRRE 135'
    card:
      type: custom:flex-table-card
      clickable: true
      max_rows: 10
      title: Bilbobus
      strict: true
      sort_by:
        - next_departures_lines
      columns:
        - hidden: true
          data: next_departures_lines
          modify: x.departure
        - name: Linea
          data: next_departures_lines
          modify: '''<ha-icon icon='' + x.icon + ''></ha-icon>'' + x.route'
        - name: Hora
          data: next_departures_lines
          modify: x.departure
        - name: Parada
          data: next_departures_lines
          modify: x.stop_name
        - name: Direcion
          data: next_departures_lines
          modify: x.headsign
      css:
        table+: 'padding: 0px'
      card_mod:
        style: |
          ha-card {
            overflow: auto;
            max-height: 500px;
          }
```
