### ISSUE TITLE
Fail to retrieve any entries in the flex table (step 5 in the documentation)

### ISSUE THREAD

**Issue by velodromen** [vingerha/gtfs2#95]
**Describe the bug**
This is most likely not a bug but instead me failing to understand how to populate the flex table. I have followed the documentation and got the sensor up and running. In step 5 I am trying to get a visualisation as the one mentioned (with flex-table-card) and the custom auto-entities. I downloaded the latter but I can't get the table to populate with rows. I think it might have to do with the "include" parameter as I can't seem to find any attributes or sensors ending in "local_stop". 

Steps/data to reproduce the behavior, e.g.
- important: url to the zip file of the **static datasource**: https://opendata.samtrafiken.se/gtfs-sweden/sweden.zip
- route ID
- stop ID
- outward/return

**Release used**
- gtfs2 
- HA type HAOS

**Additional**
Please add logs if helpfull, switch to 'debug' logging to get more details
![image](https://github.com/vingerha/gtfs2/assets/15056904/8956515a-d855-4855-b3c9-c39fa6174080)

**Comment by vingerha** [comment]
I cannot comment if you donot provide the code for the card.... please properly format between three backticks

**Comment by velodromen** [comment]
Yes :) Here is the card code (used the default code provided by you):

```
type: custom:auto-entities
filter:
  include:
    - name: '*_local_stop'
  exclude:
    - state: unavailable
card:
  type: custom:flex-table-card
  clickable: true
  max_rows: 30
  title: Local Stop dep.
  strict: true
  sort_by:
    - next_departures_lines
  columns:
    - hidden: true
      data: next_departures_lines
      modify: x.departure
    - name: Route
      data: next_departures_lines
      modify: '''<ha-icon icon='' + x.icon + ''></ha-icon>'' + x.route'
    - name: Time
      data: next_departures_lines
      modify: x.departure
    - name: Stop
      data: next_departures_lines
      modify: x.stop_name
    - name: Headsign
      data: next_departures_lines
      modify: x.headsign
  css:
    table+: 'padding: 0px'
  card_mod:
    style: |
      ha-card {
        overflow: auto;
        max-height: 500px;
      }
```

And here is a printscreen of one of the sensors:
<img width="880" alt="data" src="https://github.com/vingerha/gtfs2/assets/15056904/3069d31e-f349-41e1-88ec-bc65fc001428">
